const emoji = {
    moeda: client.emojis.cache.get("emojiMoeda"), // exemplo
    gema: client.emojis.cache.get(""),
    emblemaVIP: client.emojis.cache.get(""),
    booster: client.emojis.cache.get(""),
    certo: client.emojis.cache.get(""),
    confirmar: client.emojis.cache.get(""),
    cofre: client.emojis.cache.get(""),
    carregando: client.emojis.cache.get(""),
    escavarCategoria: client.emojis.cache.get(""),
    paCategoria: client.emojis.cache.get(""),
    fabricaCategoria: client.emojis.cache.get(""),
    PIX: client.emojis.cache.get(""),
    vigilante: client.emojis.cache.get(""),
    recusar: client.emojis.cache.get(""),
    call: client.emojis.cache.get(""),
    loja: client.emojis.cache.get(""),
    paMadeira: client.emojis.cache.get(""),
    paPedra: client.emojis.cache.get(""),
    paFerro: client.emojis.cache.get(""),
    paOuro: client.emojis.cache.get(""),
    paDiamante: client.emojis.cache.get(""),
    paRuby: client.emojis.cache.get(""),
    paMagia: client.emojis.cache.get(""),
    paArcoIris: client.emojis.cache.get(""),
    paAdamantium: client.emojis.cache.get(""),
    carvao: client.emojis.cache.get(""),
    pedra: client.emojis.cache.get(""),
    ferro: client.emojis.cache.get(""),
    ouro: client.emojis.cache.get(""),
    diamante: client.emojis.cache.get(""),
    ametista: client.emojis.cache.get(""),
    esmeralda: client.emojis.cache.get(""),
    rubi: client.emojis.cache.get(""),
    lapislazuli: client.emojis.cache.get(""),
    jadeite: client.emojis.cache.get(""),
    patente: client.emojis.cache.get(""),
    info: client.emojis.cache.get("")
}

global.emoji = emoji;